version: '3.7'

services:
  # Container for Nginx
  nginx:
    # We need some configuration for Symfony
    # Like where error log or access log will
    # be stored
    build:
      context: .
      dockerfile: ./docker-local/nginx/Dockerfile
    environment:
      - ENV=dev
    # Need to keep files and logs
    volumes:
      - ./:/var/www/company_archive/
    # Port 80 is already in use so I use 81
    ports:
      - 8500:80
    depends_on:
      - php

  # Container for PHP
  php:
    # We need some configuration for Symfony
    build:
      context: .
      dockerfile: ./docker-local/php/Dockerfile
    environment:
      - ENV=dev
    # Need to keep files and logs
    volumes:
      - ./:/var/www/company_archive/
    env_file:
      - ./.env
  node:
    image: node:14.17.3-alpine
    container_name: node
    working_dir: /app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
    links:
      - php

  # Postgres database
  db:
    container_name: company_archive_pg_container
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: company_archive
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    # Using a volume to keep the data on the database
    volumes:
      - company_archive_db:/var/lib/postgresql/data
    ports:
      - 2345:5432

  # To have an interface on Postgres
  pgadmin:
      image: dpage/pgadmin4
      ports:
          - 8089:80
      links:
          - db
      environment:
          PGADMIN_DEFAULT_EMAIL: root@root.com
          PGADMIN_DEFAULT_PASSWORD: root
      volumes:
          - ./docker-local/pgadmin/servers.json:/pgadmin4/servers.json

# The volume for the database
volumes:
  company_archive_db: {}